### PR TITLE
Tag Integration

### PR DESCRIPTION
**Pull request by fproldan**
https://github.com/agritheory/shipstation_integration/issues/9

### CODE REVIEW

**Review by agritheory — APPROVED** [review]

**Review by agritheory — CHANGES_REQUESTED** [review]
Change user email to 'Administrator'

**Review by agritheory — COMMENTED** [review]
@fproldan Does this include an override for the tag colors? I don't see a JS file

**Comment by fproldan** [comment]
@agritheory added the coloring part for tags with `color` field set

**Review by agritheory — CHANGES_REQUESTED** [review]
I added a contrast function to make for better text and tried to add the same functionality to the sales order list but I'm stuck in callback hell. @fproldan Can you give it a look?

**Comment by agritheory** [comment]
@fproldan Let's try adding tags to `frappe.boot.tags` and treat it like a client-side cache.

**Comment by agritheory** [comment]
@fproldan Added a way to show more tags
image

**Review by agritheory — APPROVED** [review]

**Pull request merged**
